---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app
  labels:
    name: voting-app
    author: venky
spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app
  template:
    metadata:
      name: voting-app
      labels:
        name : voting-app
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
...
